name: Maven release

on:
  workflow_dispatch:
    inputs:
      note:
        description: 'Notes'
        required: false
        default: 'Manual trigger'

env:
  REGISTRY: docker.io
  ACCOUNT: pcloud

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # to upload sarif files
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: github

      # https://github.com/actions/cache/blob/master/examples.md#java---maven
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure Git user
        run: |
          git config user.email "tran.q.the@gmail.com"
          git config user.name "The Tran"

      - name: Publish JAR
        run: ./mvnw -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}